/**:
    ros__parameters:
      # make sure to first plug in the endoscope camera as the first camera
      # run docker after all cameras are plugged in
      video_device: "/dev/video2"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "endoscope"
      pixel_format: "mjpeg2rgb"
      av_device_format: "YUV422P"
      image_width: 1600
      image_height: 1200
      camera_name: "endoscope"
      # reusing same camera intrinsics only for demo, should really be unique for camera2"
      camera_info_url: "package://vision_pkg/config/camera_info_endoscope.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: false
      white_balance: 4000
      autoexposure: false
      exposure: 100
      autofocus: false
      focus: -1
